Repository wecode-bootcamp-korea/28-1st-Gamsung-frontend, pull requests merged in 2022-01, with the labels that each got.

#4 [28기 진민욱]Modify: Router 컴포넌트 수정 및 Login, Signup 삭제
  src/Router.js
  src/pages/Cart/Cart.js
  src/pages/Login/Login.js
  src/pages/Sign/Sign.js
  src/pages/Signup/Signup.js
Labels: Status: Accepted

#6 [28기 박준영] Add: Footer 컴포넌트 추가
  src/Router.js
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.scss
  src/pages/Cart/Cart.js
  src/pages/Login/Login.js
  src/pages/Sign/Sign.js
  src/pages/Signup/Signup.js
Labels: Status: Accepted

#5 [28기 진민욱] Add: Nav 컴포넌트 기능 및 스타일 추가
  src/components/Navbar.js
  src/components/Navbar/NavCart/NavCart.js
  src/components/Navbar/NavCart/NavCart.scss
  src/components/Navbar/NavCart/NavCartList/NavCartItem.js
  src/components/Navbar/NavCart/NavCartList/NavCartItem.scss
  src/components/Navbar/NavMenu/MenuCategory/Device/Device.js
  src/components/Navbar/NavMenu/MenuCategory/Device/Device.scss
  src/components/Navbar/NavMenu/MenuCategory/MenuCategory.js
  src/components/Navbar/NavMenu/MenuCategory/MenuCategory.scss
  src/components/Navbar/NavMenu/NavMenu.js
  src/components/Navbar/NavMenu/NavMenu.scss
  src/components/Navbar/NavSearch/NavSearch.js
  src/components/Navbar/NavSearch/SearchBar/SearchBar.js
  src/components/Navbar/NavSearch/SearchBar/SearchBar.scss
  src/components/Navbar/Navbar.js
  src/components/Navbar/Navbar.scss
  src/components/Navbar/UserMenu/UserMenu.js
  src/components/Navbar/UserMenu/UserMenu.scss
  src/components/Navbar/UserMenu/UserMenuItem/UserMenuItem.js
  src/components/Navbar/UserMenu/UserMenuItem/UserMenuItem.scss
  src/pages/Cart/Cart.js
  src/pages/Login/Login.js
  src/pages/Main/Main.js
  src/pages/Sign/Sign.js
  src/pages/Signup/Signup.js
Labels: Status: Accepted

#7 [28기 박준영] 제품 상세페이지 스타일 수정 및 오류 수정
  src/Router.js
  src/pages/Main/Main.js
  src/pages/ProductDetail/ProductCarousel/ProductCarousel.jsx
  src/pages/ProductDetail/ProductCarousel/ProductCarousel.scss
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductInfo/Dropdown/Dropdown.jsx
  src/pages/ProductDetail/ProductInfo/Dropdown/Dropdown.scss
  src/pages/ProductDetail/ProductInfo/ProductInfo.jsx
  src/pages/ProductDetail/ProductInfo/ProductInfo.scss
Labels: Status: 리뷰 요청

#3 [28기 윤종호]Add: 상품리스트 레이아웃 및 UI 구현 1차 & 필터링 기능 구현 완료
  .vscode/settings.json
  public/data/Products/mockData.json
  public/images/images.md
  public/images/products/gamsung_images/top-image.jpg
  src/pages/Products/Filter/FilterElement/FilterElement.js
  src/pages/Products/Filter/FilterElement/FilterElement.scss
  src/pages/Products/Filter/ProductsFilter.js
  src/pages/Products/Filter/ProductsFilter.scss
  src/pages/Products/ProductCard/ProductCard.js
  src/pages/Products/ProductCard/ProductCard.scss
  src/pages/Products/Products.js
  src/pages/Products/Products.scss
Labels: Status: 리뷰 요청

#9 [28기 박준영] Layout 컴포넌트 생성 및 오류수정
  src/Router.js
  src/components/Layout.jsx
  src/pages/Main/MainCarousel/MainCarousel.scss
  src/pages/ProductDetail/ProductDetail.jsx
Labels: Status: 리뷰 요청

#2 [28기 진민욱] Sign 페이지 1차 완성
  src/components/AuthHeader/AuthHeader.js
  src/components/AuthHeader/AuthHeader.scss
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductDetail/ProductInfo/ProductInfo.jsx
  src/pages/Sign/Sign.js
  src/pages/Sign/SignForm/SignForm.js
  src/pages/Sign/SignForm/SignForm.scss
  src/pages/Sign/SignForm/SignFormLayout.js
  src/pages/Sign/SignForm/SignInput/SignInput.js
  src/pages/Sign/SignForm/SignInput/SignInput.scss
  src/pages/Sign/sign.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#8 [28기 진민욱]Add: Cart 페이지 1차 완성
  src/components/Navbar.js
  src/components/Navbar/Navbar.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartList/CartItem/CartItem.js
  src/pages/Cart/CartList/CartItem/CartItem.scss
  src/pages/Cart/CartList/CartList.js
  src/pages/Cart/CartList/CartList.scss
  src/pages/Cart/CartOrder/CartOrder.js
  src/pages/Cart/CartOrder/CartOrder.scss
  src/pages/Cart/CartOrder/CartOrderAddress/CartOrderAddress.js
  src/pages/Cart/CartOrder/CartOrderAddress/CartOrderAddress.scss
  src/pages/Cart/CartOrder/CartOrderMenu/CartOrderMenu.js
  src/pages/Cart/CartOrder/CartOrderMenu/CartOrderMenu.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중
